### ISSUE TITLE
When will the deprecation be enforced in Core not User-land?

### ISSUE THREAD

**Issue by jacktuck** [mcollina/make-promises-safe#5]
@mcollina Nice work on this, thanks!

Sorry to make an issue just to ask a question, let me know if i should have asked some other way.

Anyway, I was wondering when this deprecation will be enforced? i.e. when will uncaught promise rejections actually kill the process?

Nightly builds don't seem to be, even for v9.

```
nvm use 9 && node -e 'Promise.reject()'
Now using node v9.0.0-nightly20170620d2913384aa (npm v5.0.3)
(node:70293) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): undefined
(node:70293) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jacktuck** [comment]
`--throw-deprecation` makes me thing deprecations aren't often enforced or something? IDK, i've gone down a bit of a rabbit hole.

**Comment by mcollina** [comment]
I have no trimeframe for that. 

Not sure if this would throw with `--throw-deprecation`.

cc @jasnell.

**Comment by jacktuck** [comment]
@mcollina Thanks for quick reply! 

Yeah it does seem to throw with the flag.

```nvm use 9 && node --throw-deprecation -e 'Promise.reject()'
Now using node v9.0.0-nightly20170620d2913384aa (npm v5.0.3)
internal/process/warning.js:151
        throw warning;
        ^

DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:69:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:86:11)
    at runMicrotasksCallback (internal/process/next_tick.js:127:9)
    at _combinedTickCallback (internal/process/next_tick.js:134:7)
    at process._tickCallback (internal/process/next_tick.js:201:9)
    at evalScript (bootstrap_node.js:435:13)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:575:3
```

**Comment by mcollina** [comment]
That is different from what this module does. This prints the stacktrace of the original error, not of the deprecation.
